# Конфигурация плагина AngerFermaRuna
# Автор: Vallidova

# Настройки руны огородника
runa:
  # Название предмета руны
  # Здесь можно использовать цветовые коды &a, &b и т.д.
  name: "&aРуна Огородника"
  # Материал для руны (по умолчанию - зеленый краситель)
  # Укажите ID материала из Minecraft (например, DIAMOND, EMERALD, GOLDEN_APPLE и т.д.)
  material: "LIME_DYE"
  # Свечение предмета (true/false)
  # Если true - предмет будет иметь эффект зачарования
  glow: true
  # Кулдаун руны в секундах
  # Интервал времени, через который можно снова использовать руну
  cooldown: 10
  # Радиус действия руны (в блоках)
  # Определяет, насколько далеко от игрока будут расти растения
  radius: 5
  # Максимальное количество стадий роста
  # Технический параметр, не меняйте без необходимости
  max-growth-stages: 7
  # Лоры предмета (максимум 8)
  # Строки описания, которые отображаются при наведении на предмет
  # Можно использовать цветовые коды &a, &b и т.д.
  lore:
    - "&7Руна для ускорения роста растений"
    - "&7Присядьте, чтобы активировать руну"
    - ""
    - "&7Радиус действия: &a5 блоков"
    - "&7Кулдаун: &a10 секунд"
    - ""
    - "&8Создано мастером рун"
    - "&8Древний артефакт фермеров"

# Автопересадка растений при ломании руной
replanting:
  # Включить/выключить автопересадку при ломании руной (true/false)
  # Если true - растения будут автоматически пересаживаться при ломании руной
  enabled: true
  # Показывать частицы при пересадке (true/false)
  # Если true - при пересадке будут отображаться частицы
  show-particles: true
  # Воспроизводить звук при пересадке (true/false)
  # Если true - при пересадке будет проигрываться звук
  play-sound: true

# Какие культуры будут расти при использовании руны
# Для каждой культуры можно указать true (включено) или false (выключено)
crops:
  wheat: true    # Пшеница
  carrots: true  # Морковь
  potatoes: true # Картофель
  beetroots: true # Свекла
  sweet_berries: true # Сладкие ягоды

# Настройки уведомлений для администраторов
admin-notifications:
  # Включить/выключить уведомления для администраторов
  # Если true - администраторы будут получать уведомления
  enabled: true
  # Показывать title при первой выдаче руны
  title:
    # Включить/выключить показ заголовка
    # Если true - при первом получении руны будет показан заголовок
    enabled: true
    # Время появления заголовка в тиках (20 тиков = 1 секунда)
    # Определяет, как долго заголовок будет плавно появляться
    fade-in: 10
    # Время отображения заголовка в тиках (20 тиков = 1 секунда)
    # Определяет, как долго заголовок будет видимым на экране
    stay: 70
    # Время исчезновения заголовка в тиках (20 тиков = 1 секунда)
    # Определяет, как долго заголовок будет плавно исчезать
    fade-out: 20 